/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mac.variables;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Usuario
 */
public class VariablesForm extends javax.swing.JFrame {

    /**
     * Creates new form Variables
     */
    LinkedList<Variable> listaDeVariables = new LinkedList<>();
    final DefaultListModel nombresDeVariables = new DefaultListModel();
    final DefaultListModel valoresDeVariables = new DefaultListModel();

    int posicionVariableSeleccionada = -1;
    int posicionValorSeleccionado = -1;
    boolean varEliminada = false;
    boolean valEliminado = false;

    public VariablesForm() {
        initComponents();
        nombres.setModel(nombresDeVariables);
        valores.setModel(valoresDeVariables);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        numerica = new javax.swing.JRadioButton();
        escalar = new javax.swing.JRadioButton();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        guardarNombre = new javax.swing.JButton();
        borrarNombre = new javax.swing.JButton();
        guardarValor = new javax.swing.JButton();
        borrarValor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nuevaVar = new javax.swing.JButton();
        eliminarVar = new javax.swing.JButton();
        nuevoVal = new javax.swing.JButton();
        eliminarVal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nombres = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        valores = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Nombre");

        jLabel4.setText("Valor");

        nombre.setEnabled(false);

        valor.setEnabled(false);

        tipos.add(numerica);
        numerica.setSelected(true);
        numerica.setText("Numerica");

        tipos.add(escalar);
        escalar.setText("Escalar");

        guardar.setText("Guardar");

        cancelar.setText("Cancelar");

        guardarNombre.setText("_/");
        guardarNombre.setEnabled(false);
        guardarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarNombreMouseClicked(evt);
            }
        });

        borrarNombre.setText("X");
        borrarNombre.setEnabled(false);
        borrarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarNombreMouseClicked(evt);
            }
        });

        guardarValor.setText("_/");
        guardarValor.setEnabled(false);
        guardarValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarValorMouseClicked(evt);
            }
        });

        borrarValor.setText("X");
        borrarValor.setEnabled(false);
        borrarValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarValorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(cancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(valor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(guardarNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(borrarNombre))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(guardarValor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(borrarValor))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(guardar)
                                .addGap(49, 49, 49)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numerica)
                            .addComponent(escalar))
                        .addGap(160, 160, 160))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(numerica)
                    .addComponent(guardarNombre)
                    .addComponent(borrarNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(escalar)
                    .addComponent(guardarValor)
                    .addComponent(borrarValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(cancelar))
                .addGap(6, 6, 6))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        nuevaVar.setText("Nueva Var");
        nuevaVar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevaVarMouseClicked(evt);
            }
        });
        jPanel2.add(nuevaVar);

        eliminarVar.setText("Eliminar Var");
        eliminarVar.setEnabled(false);
        eliminarVar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarVarMouseClicked(evt);
            }
        });
        jPanel2.add(eliminarVar);

        nuevoVal.setText("Nuevo Val");
        nuevoVal.setEnabled(false);
        nuevoVal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoValMouseClicked(evt);
            }
        });
        jPanel2.add(nuevoVal);

        eliminarVal.setText("Eliminar Val");
        eliminarVal.setEnabled(false);
        eliminarVal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarValMouseClicked(evt);
            }
        });
        jPanel2.add(eliminarVal);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Variables");
        jPanel4.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        nombres.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                nombresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(nombres);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("valores");
        jPanel5.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        valores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                valoresValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(valores);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaVarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaVarMouseClicked
        habilitarNombre();
        posicionVariableSeleccionada = -1;
    }//GEN-LAST:event_nuevaVarMouseClicked

    private void borrarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarNombreMouseClicked
        nombre.setText("");
        nombre.requestFocusInWindow();
    }//GEN-LAST:event_borrarNombreMouseClicked

    private void borrarValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarValorMouseClicked
        valor.setText("");
        valor.requestFocusInWindow();
    }//GEN-LAST:event_borrarValorMouseClicked

    private void guardarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarNombreMouseClicked
        if (!nombre.getText().isEmpty()) {
            if (posicionVariableSeleccionada >= 0) {
                listaDeVariables.get(posicionVariableSeleccionada).setNombre(nombre.getText());
                nombresDeVariables.setElementAt(nombre.getText(), posicionVariableSeleccionada);
            } else {
                listaDeVariables.add(new Variable(numerica.isSelected(), nombre.getText()));
                nombresDeVariables.addElement(nombre.getText());
                posicionVariableSeleccionada = listaDeVariables.size() - 1;
                eliminarVar.setEnabled(true);
            }
            habilitarValor();
            valor.requestFocusInWindow();

        }
    }//GEN-LAST:event_guardarNombreMouseClicked

    private void guardarValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarValorMouseClicked
        if (!valor.getText().isEmpty()) {
            Variable var = listaDeVariables.get(posicionVariableSeleccionada);
            if (var.esNumerica) {
                if (var.getIntervaloNumerico().isEmpty()) {
                    var.agregarIntervalo(valor.getText());
                    valoresDeVariables.addElement(valor.getText());
                } else {
                    var.modificarIntervalo(valor.getText());
                    valoresDeVariables.setElementAt(valor.getText(), 0);
                }
            } else {
                if (posicionValorSeleccionado >= 0) {
                    valoresDeVariables.setElementAt(valor.getText(), posicionValorSeleccionado);
                    var.modificarValor(valor.getText(), posicionValorSeleccionado);

                } else {
                    var.valoresEscalares.add(valor.getText());
                    posicionValorSeleccionado = var.valoresEscalares.size() - 1;
                    valoresDeVariables.addElement(valor.getText());
                }

            }
        }

    }//GEN-LAST:event_guardarValorMouseClicked

    private void nombresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_nombresValueChanged

        if (!varEliminada) {
            posicionValorSeleccionado = -1;
            posicionVariableSeleccionada = nombres.getSelectedIndex();
            eliminarVar.setEnabled(true);
            habilitarNombre();
            habilitarValor();
            Variable v = listaDeVariables.get(posicionVariableSeleccionada);
            nombre.setText(v.getNombre());
            valoresDeVariables.clear();
            if (v.esNumerica) {
                numerica.setSelected(true);
                if (!v.getIntervaloNumerico().isEmpty()) {
                    valoresDeVariables.addElement(v.getIntervaloNumerico());
                }
            } else {
                escalar.setSelected(true);
                for (String valor : v.getValoresEscalares()) {
                    valoresDeVariables.addElement(valor);
                }
            }
            nuevoVal.setEnabled(true);
        }

        varEliminada = false;


    }//GEN-LAST:event_nombresValueChanged

    private void valoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_valoresValueChanged
        if (!valEliminado) {
            posicionValorSeleccionado = valores.getSelectedIndex();
            habilitarValor();
            Variable var = listaDeVariables.get(posicionVariableSeleccionada);
            if (var.esNumerica) {
                valor.setText(var.getIntervaloNumerico());
            } else {
                if(posicionValorSeleccionado>=0)
                valor.setText(var.getValoresEscalares().get(posicionValorSeleccionado));
            }
            eliminarVal.setEnabled(true);
        }
        valEliminado = false;
    }//GEN-LAST:event_valoresValueChanged

    private void eliminarVarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarVarMouseClicked
        varEliminada = true;
        nombresDeVariables.remove(posicionVariableSeleccionada);
        listaDeVariables.remove(posicionVariableSeleccionada);
        posicionVariableSeleccionada = -1;
        posicionValorSeleccionado = -1;
        nombre.setText("");
        nombre.setEnabled(false);
        guardarNombre.setEnabled(false);
        borrarNombre.setEnabled(false);
        valor.setText("");
        valor.setEnabled(false);
        guardarValor.setEnabled(false);
        borrarValor.setEnabled(false);

        eliminarVar.setEnabled(false);
        eliminarVal.setEnabled(false);
        nuevoVal.setEnabled(false);


    }//GEN-LAST:event_eliminarVarMouseClicked

    private void eliminarValMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarValMouseClicked
        valEliminado = true;
        valoresDeVariables.remove(posicionValorSeleccionado);
        listaDeVariables.get(posicionVariableSeleccionada).getValoresEscalares().remove(posicionValorSeleccionado);
        posicionValorSeleccionado = -1;

        valor.setText("");
        valor.setEnabled(false);
        guardarValor.setEnabled(false);
        borrarValor.setEnabled(false);

        eliminarVar.setEnabled(false);
        eliminarVal.setEnabled(false);
        nuevoVal.setEnabled(false);
    }//GEN-LAST:event_eliminarValMouseClicked

    private void nuevoValMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoValMouseClicked
        posicionValorSeleccionado = -1;
        habilitarValor();
        valor.requestFocusInWindow();
        eliminarVal.setEnabled(false);
    }//GEN-LAST:event_nuevoValMouseClicked
    public void habilitarNombre() {
        nombre.setText("");
        nombre.setEnabled(true);
        nombre.requestFocusInWindow();
        guardarNombre.setEnabled(true);
        borrarNombre.setEnabled(true);
        valor.setText("");
        valor.setEnabled(false);
        guardarValor.setEnabled(false);
        borrarValor.setEnabled(false);
    }

    public void habilitarValor() {
        valor.setText("");
        valor.setEnabled(true);
        guardarValor.setEnabled(true);
        borrarValor.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VariablesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VariablesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VariablesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VariablesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VariablesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarNombre;
    private javax.swing.JButton borrarValor;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton eliminarVal;
    private javax.swing.JButton eliminarVar;
    private javax.swing.JRadioButton escalar;
    private javax.swing.JButton guardar;
    private javax.swing.JButton guardarNombre;
    private javax.swing.JButton guardarValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombre;
    private javax.swing.JList<String> nombres;
    private javax.swing.JButton nuevaVar;
    private javax.swing.JButton nuevoVal;
    private javax.swing.JRadioButton numerica;
    private javax.swing.ButtonGroup tipos;
    private javax.swing.JTextField valor;
    private javax.swing.JList<String> valores;
    // End of variables declaration//GEN-END:variables
}
